#  _____              _      _
# |__  /___  ___ ___ (_) ___| |_ _   _
#   / // __|/ __/ _ \| |/ _ \ __| | | |
#  / /_\__ \ (_| (_) | |  __/ |_| |_| |
# /____|___/\___\___/|_|\___|\__|\__, |
#                                |___/


#用于检测配置文件版本
version: 1.0.8alpha

#默认创建公会金额(浮点类型必须不能删除.0)
createSocietyMoney: 100000.0

#每次求婚最低金额
proposeMoney: 100000.0

#插件默认使用的语言文件(暂时就是仅仅提供了中文语言文件)
language: zh-CN.yml

#是否开启聊天显示
isChat: true

#称号格式
chatFormat: "${privilege}§r§7[§6${world}§7][${title}§7][§e${societyName}§7]§7[${marry}§7]§b${playerName}§f ${message}"

#是否显示底部信息 （如果有底部显示建议false）
isTip: false

#底部显示格式
tipText: "§c✎手持>${itemID}  §9☣地图>${levelName}  §d♨生命>${h}/${mh}  §f۞在线>${online}/${maxplayer}  §b❉延迟>${ms} \n §2✤职位>${post}
                   §e♈金币>${money}   §7☼公会>${societyName}  §3❤公会等级>${societyGrade}"

#是否开启玩家标签设置
isSetNameTag: true

#玩家标签格式化内容
nameTagFormat: "${privilege}§r §l§3❤§r §e${title} §l§a✤§r §b${societyName} §l§a✤§r §9${name}"

#称号商店格式内容
titleShopFormat:
  - "§7[§c称§a号§b商店§7]"
  - "§7[§e称号§b☼§f${title}§7]"
  - "§7[售价§b❤§e${money}§7]"
  - "§c快速抢购"

#公会商店格式内容
societyShopFormat:
  - "§7[§c公§a会§b商店§7]"
  - "§7[§b物品->§a${itemName}§e数量§f:§c${count}§7]"
  - "§7[售价§b❤§e${itemPrice}§7]"
  - "§c所属公会:§a${societyName}"

#此配置信息暂时勿动!
post:
  - {
    name: 会长, #名称
    grade: 20, #职位等级
    count: 1 #可拥有数量 (会长必须唯一) -1代表无限
  }
  - {
    name: 副会长,
    grade: 3,
    count: 1
  }
  - {
    name: 元老,
    grade: 2,
    count: 2
  }
  - {
    name: 精英,
    grade: 1,
    count: 1
  }

#公会等级
#配置格式如下 公会等级: [最大成员数量,升级所需要的金额]
等级1:
  - 10
  - 1000
等级2:
  - 20
  - 10000
等级3:
  - 30
  - 20000
等级4:
  - 40
  - 40000
等级5:
  - 50
  - 80000
等级6:
  - 60
  - 100000
等级7:
  - 70
  - 1000000

