##窗口配置文件

#########公会窗口配置#########
#公会功能窗口标题
societyWindow.title: §e公会功能列表
#创建公会窗口标题
createSocietyWindow.title: §e创建公会
#会长管理窗口标题
presidentWindow.title: §l§b${societyName} §e管理
#设置职位窗口标题
setJobWindow.title: §e设置职位
#移除成员列表窗口标题
removeMemberWindow.title: §e移除成员列表
#玩家申请加入公会列表
playerApplyListWindow.title: §e玩家申请加入公会列表
#成员列表窗口标题
memberListWindow.title: §e成员列表
#公会等级排行榜窗口
levelRankWindow.title: §e公会等级排行榜
#公会贡献排行榜
contributionRankingWindow.title: §e公会贡献排行榜
#公会贡献窗口标题
contributionWindow.title: §e公会贡献
#创建公会商店窗口标题
createSocietyShopWindow.title: §e创建公会商店
#管理公会窗口标题
societyAdminWindow.title: §e管理公会
#设置公会等级窗口标题
setGradeWindow.title: §e设置公会等级
#解散公会窗口标题
dissolveWindow.title: §e解散玩家公会
#公会列表标题
societyListWindow.title: §e公会列表

#公会功能窗口按钮1
societyWindow.createSociety.button: §e创建公会
#公会功能窗口按钮2
societyWindow.managerSociety.button: §e管理公会
#公会功能窗口按钮3
societyWindow.quitSociety.button: §e退出公会
#公会功能窗口按钮4
societyWindow.joinSociety.button: §e加入公会
#公会功能窗口按钮5
societyWindow.memberList.button: §e公会成员列表
#公会功能窗口按钮6
societyWindow.contributionRanking.button: §e公会经济贡献排行榜
#公会功能窗口按钮7
societyWindow.levelRank.button: §e公会等级排行榜
#公会功能窗口按钮8
societyWindow.contribution.button: §e贡献经济
#公会功能窗口按钮9
societyWindow.createShopWindow.button: §e创建公会商店
#公会功能窗口按钮10
societyWindow.societyChat.button: §a开启§e-§c关闭§e公会聊天
#公会功能窗口按钮11
societyWindow.tpaSociety.button: §e传送至公会出生点

#会长管理窗口按钮1
presidentWindow.setJobWindow.button: §e设置公会职
#会长管理窗口按钮2
presidentWindow.playerApplyList.button: §e查看玩家申请列表
#会长管理窗口按钮3
presidentWindow.upGrade.button: §e升级公会等级
#会长管理窗口按钮4
presidentWindow.removeMember.button: §e移除公会成员
#会长管理窗口按钮5
presidentWindow.dissolve.button: §e解散公会

#管理公会窗口按钮1
societyAdminWindow.setSocietyGrade.button: §e设置公会等级
#管理公会窗口按钮2
societyAdminWindow.setSocietyContribution.button: §e设置公会贡献值
#管理公会窗口按钮3
societyAdminWindow.dissolve.button: §e解散玩家公会
#管理公会窗口按钮4
societyAdminWindow.setSpawn.button: §e设置公会出生点

#创建公会按钮1图片路径
societyWindow.createSociety.button.imgPath: textures/ui/anvil_icon.png
#管理公会按钮图片路径
societyWindow.managerSociety.button.imgPath: textures/ui/MashupIcon.png
#退出公会按钮图片路径
societyWindow.quitSociety.button.imgPath: textures/ui/cancel
#加入公会按钮图片路径
societyWindow.joinSociety.button.imgPath: textures/ui/recipe_book_expand_icon.png
#公会成员列表按钮图片路径
societyWindow.memberList.button.imgPath: textures/ui/copy
#公会经济贡献排行榜按钮图片路径
societyWindow.contributionRanking.button.imgPath: textures/ui/wither_effect.png
#公会等级排行榜按钮图片
societyWindow.levelRank.button.imgPath: textures/ui/feedIcon
#贡献经济按钮内容图片
societyWindow.contribution.button.imgPath: textures/ui/wither_heart_flash.png
#创建公会商店按钮图片
societyWindow.createShopWindow.button.imgPath: textures/ui/conduit_power_effect.png
#公会聊天按钮图片
societyWindow.societyChat.button.imgPath: textures/ui/Feedback.png
#传送到公会出生点按钮
societyWindow.tpaSociety.button.imgPath: textures/ui/restore_arrow_default.png

#会长管理窗口按钮1图片
presidentWindow.setJobWindow.button.imgPath: textures/ui/dev_glyph_color.png
#会长管理窗口按钮2图片
presidentWindow.playerApplyList.button.imgPath: textures/ui/copy
#会长管理窗口按钮3图片
presidentWindow.upGrade.button.imgPath: textures/ui/share_apple.png
#会长管理窗口按钮4图片
presidentWindow.removeMember.button.imgPath: textures/ui/cancel.png
#会长管理窗口按钮5图片
presidentWindow.dissolve.button.imgPath: textures/ui/trash_default.png

#管理公会窗口按钮1图片
societyAdminWindow.setSocietyGrade.button.imgPath: textures/ui/dev_glyph_color.png
#管理公会窗口按钮2图片
societyAdminWindow.setSocietyContribution.button.imgPath: textures/ui/dev_glyph_color.png
#管理公会窗口按钮3图片
societyAdminWindow.dissolve.button.imgPath: textures/ui/realms_red_x.png

#########特权窗口配置#########
#VIP窗口标题
privilegeWindow.title: §eVIP特权
#SVIP窗口标题
advancedPrivilegeWindow.title: §eSVIP特权
#VIP信息窗口
privilegeInfoWindow.title: §l§b${playername} §r§e的特权信息
#特权管理窗口标题
privilegeManagerWindow.title: §e特权管理
#特权信息列表窗口标题
privilegeListWindow.title: §e特权信息列表
#移除玩家特权窗口标题
removePrivilegeWindow.title: §e移除玩家特权
#设置玩家特权窗口标题
setPrivilegeWindow.title: §e设置玩家特权

#VIP窗口生存飞行按钮
privilegeWindow.survivalFlight.button: ${flight} §e生存飞行
#VIP窗口查看VIP信息按钮
privilegeWindow.openInfo.button: §e我的VIP信息
#SVIP窗口打开VIP功能窗口按钮
advancedPrivilegeWindow.openVip.button: §e打开VIP功能
#SVIP窗口开关创造模式按钮
advancedPrivilegeWindow.switchCreate.button: ${create} §e创造模式
#SVIP窗口SVIP信息按钮
advancedPrivilegeWindow.openInfo.button: §e我的SVIP信息
#特权管理窗口设置设置特权按钮
privilegeManagerWindow.setPrivilege.button: §e设置特权
#特权管理窗口移除特权按钮
privilegeManagerWindow.removePrivilege.button: §e移除特权
#特权管理窗口查看拥有特权玩家
privilegeManagerWindow.viewPrivilegePlayer.button: §e查看拥有特权玩家


#VIP窗口生存生存飞行图片路径
privilegeWindow.survivalFlight.button.imgPath: textures/ui/code_makecode_default.png
#VIP窗口查看VIP信息按钮图片
privilegeWindow.viewVip.button.imgPath: textures/ui/Friend1.png
#SVIP窗口VIP功能图片路径
advancedPrivilegeWindow.openVip.button.imgPath: textures/ui/heart_flash.png
#SVIP窗口开启创造模式图片路径
advancedPrivilegeWindow.switchCreate.button.imgPath: textures/ui/icon_armor.png
#SVIP窗口SVIP信息按钮图片路径
advancedPrivilegeWindow.openInfo.button.imgPath: textures/ui/Friend1.png
#特权管理窗口按钮1图片路径
privilegeManagerWindow.setPrivilege.button.imgPath: textures/ui/automation_glyph_color.png
#特权管理窗口按钮2图片路径
privilegeManagerWindow.removePrivilege.button.imgPath: textures/ui/cancel.png
#特权管理窗口按钮3图片路径
privilegeManagerWindow.viewPrivilegePlayer.button.imgPath: textures/ui/copy


#########称号窗口配置#########
#称号列表窗口标题
titleWindow.title: §e称号列表
#称号管理窗口标题
titleManagerWindow.title: §e称号管理
#设置称号窗口标题
setTitleWindow.title: §e设置称号
#移除称号窗口标题
removeTitleWindow.title: §e移除称号
#创建称号商店窗口标题
createTitleShopWindow.title: §e创建称号商店

#称号管理窗口按钮1
titleManagerWindow.setTitle.button: §e设置称号
#称号管理窗口按钮2
titleManagerWindow.removeTitle.button: §e移除称号
#称号管理窗口按钮3
titleManagerWindow.createTitleShop.button: §e创建称号商店

#称号管理窗口按钮1图片路径
titleManagerWindow.setTitle.button.imgPath: textures/ui/dev_glyph_color.png
#称号管理窗口按钮2图片路径
titleManagerWindow.removeTitle.button.imgPath: textures/ui/redX1.png
#称号管理窗口按钮3图片路径
titleManagerWindow.createTitleShop.button.imgPath: textures/ui/anvil_icon.png


#########结婚窗口配置#########
#结婚窗口配置标题
marryWindow.title: §e结婚窗口
#添加公共资产窗口标题
addPublicFunds.title: §e添加公共资产
#求婚窗口标题
proposeWindow.title: §e求婚
#结婚公共资产排行榜窗口标题
moneyRankWindow.title: §e公共资产排行榜
#结婚管理窗口标题
marryAdminWindow.title: §e结婚管理
#移除夫妻窗口标题
removeMarryWindow.title: §e移除夫妻窗口
#设置夫妻资产窗口
setMarryMoneyWindow.title: §e设置夫妻资产窗口


#结婚窗口按钮1
marryWindow.propose.button: §e求婚
#结婚窗口按钮2
marryWindow.addPublicFunds.button: §e添加公共资产
#结婚窗口按钮3
marryWindow.transfer.button: §e传送到情侣身边
#结婚窗口按钮4
marryWindow.divorceMarry.button: §e离婚
#结婚窗口按钮5
marryWindow.moneyRankWindow.button: §e夫妻公共资产排行榜
#结婚管理窗口按钮1
marryAdminWindow.setContribution.button: §e设置夫妻公共资产
#结婚管理窗口按钮2
marryAdminWindow.remove.button: §e移除指定夫妻

#结婚窗口按钮1图片路径
marryWindow.propose.button.imgPath: textures/ui/regeneration_effect.png
#结婚窗口按钮2图片路径
marryWindow.addPublicFunds.button.imgPath: textures/ui/xbox_dpad.png
#结婚窗口按钮3图片路径
marryWindow.transfer.button.imgPath: textures/ui/restore_arrow_default.png
#结婚窗口按钮4图片路径
marryWindow.divorceMarry.button.imgPath: textures/ui/heart_half.png
#结婚窗口按钮5图片路径
marryWindow.moneyRankWindow.button.imgPath: textures/ui/absorption_effect.png
#结婚管理窗口按钮1图片路径
marryAdminWindow.setContribution.button.imgPath: textures/ui/dev_glyph_color.png
#结婚管理窗口按钮2图片路径
marryAdminWindow.remove.button.imgPath: textures/ui/dev_glyph_color.png

#消息窗口标题
messageWindow.title: §e消息提示
#确认窗口标题
modalWindow.title: §e确认提示

#消息窗口按钮1
messageWindow.close.button: §e关闭窗口
#消息窗口按钮1.1
messageWindow.back.button: §e返回上级

#消息窗口按钮1图片路径
messageWindow.close.button.imgPath: textures/ui/Friend1.png
#消息窗口按钮1.1图片路径
messageWindow.back.button.imgPath: textures/ui/Friend1.png
